### ISSUE TITLE
triple click on moving multiple cards

### ISSUE THREAD

**Issue by Daver067** [Daver067/card-games#26]
performed a quick triple click on move than 1 card that was moving from one tableau to the other, the third click caught a card that was mid move and highlighted it as a single click, but it must have caught it mid transition so the data was skewed. The card stayed highlighted until i clicked it again. 
Clear all info may be actuating at the wrong time, or maybe the listener needs to check for the cards state to be 'idle' or 'available'

**Comment by chartley1988** [comment]
Fixed with 8b60b8c
